export type FranChallengeHand = {
  name: string,
  description: string,
  points: number,
  probability?: number,
  canComposite: boolean,
  isPokerHand: boolean,
}

export const franChallengeHands: FranChallengeHand[] = [
  {
    name: 'ふらんちゃん',
    description: '「ふらんちゃん」の並びになっている',
    probability: 781.25,
    points: 5000000,
    canComposite: false,
    isPokerHand: false,
  },
  {
    name: '逆から読んでも',
    description: '「んちゃんらふ」の並びになっている',
    probability: 781.25,
    points: 25000,
    canComposite: false,
    isPokerHand: false,
  },
  {
    name: '順不同明王',
    description: '「ふ」「ら」「ちゃ」が1つずつ、「ん」が2つ入っている',
    probability: 13.02,
    points: 5,
    canComposite: true,
    isPokerHand: false,
  },
  {
    name: '新種の果実、ちゃふらんす',
    description: '「ちゃふらん」が入っている',
    points: 5,
    canComposite: true,
    isPokerHand: false,
  },
  {
    name: '満場一致',
    description: '5文字全てがいずれか1種類の文字',
    probability: 91.93,
    points: 3,
    canComposite: true,
    isPokerHand: false,
  },
  {
    name: 'パーソナルミラー',
    description: '1文字目と5文字目、2文字目と4文字目が同じ文字',
    probability: 12.75,
    points: 3,
    canComposite: true,
    isPokerHand: false,
  },
  {
    name: '誰よその女！',
    description: '先頭3文字が「ふ」「ら」「ん」のいずれか、かつ「ちゃん」で終わる',
    points: 3,
    canComposite: true,
    isPokerHand: false,
  },
  {
    name: '4と鳴く犬',
    description: '同じ文字が4つ入っている',
    points: 3,
    canComposite: true,
    isPokerHand: true,
  },
  {
    name: 'ふらハウス',
    description: '同じ文字が3つ入っており、別の文字のペアが入っている',
    points: 3,
    canComposite: true,
    isPokerHand: true,
  },
  {
    name: '上の句揃え',
    description: '「ふらん」から始まる',
    probability: 62.46,
    points: 2,
    canComposite: true,
    isPokerHand: false,
  },
  {
    name: '下の句揃え',
    description: '「ちゃん」で終わる',
    probability: 12.50,
    points: 2,
    canComposite: true,
    isPokerHand: false,
  },
  {
    name: 'ロケットランチャー',
    description: '「らんちゃ」が入っている',
    probability: 20.83,
    points: 2,
    canComposite: true,
    isPokerHand: false,
  },
  {
    name: '出荷よ(´・ω・`)',
    description: '「らんらん」が入っている',
    probability: 78.16,
    points: 2,
    canComposite: true,
    isPokerHand: false,
  },
  {
    name: 'ちゃらんぷらん',
    description: '「ちゃらん」が入っている',
    points: 2,
    canComposite: true,
    isPokerHand: false,
  },
  {
    name: 'ふ2（りゃん）ちゃん',
    description: '同じ文字のペアが2つ入っている',
    points: 2,
    canComposite: true,
    isPokerHand: true,
  },
  {
    name: 'デコ助野郎',
    description: '同じ文字が3つ入っている',
    points: 2,
    canComposite: true,
    isPokerHand: true,
  },
  {
    name: '一心ふらん',
    description: '「ふらん」が入っている',
    probability: 20.84,
    points: 1,
    canComposite: true,
    isPokerHand: false,
  },
  {
    name: 'ワンちゃんある',
    description: '「ちゃん」が入っている',
    probability: 3.32,
    points: 1,
    canComposite: true,
    isPokerHand: false,
  },
  {
    name: 'ちゃふ台返し',
    description: '「ちゃふ」が入っている',
    points: 1,
    canComposite: true,
    isPokerHand: false,
  },
  {
    name: 'ふ1（ワン）ちゃん',
    description: '同じ文字のペアが1つ入っている',
    points: 2,
    canComposite: true,
    isPokerHand: true,
  },
] as const
